# Generated by Django 5.0.14 on 2025-12-23 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='source_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.uploadedfile'),
        ),
        migrations.AddField(
            model_name='income',
            name='source_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='core.uploadedfile'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('food', 'Еда'), ('transport', 'Транспорт'), ('entertainment', 'Развлечения'), ('shopping', 'Покупки'), ('subscriptions', 'Подписки'), ('education', 'Образование'), ('health', 'Здоровье'), ('beauty', 'Красота'), ('games', 'Игры'), ('other', 'Другое')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_type',
            field=models.CharField(choices=[('allowance', 'Карманные деньги'), ('part_time', 'Подработка'), ('gift', 'Подарок'), ('freelance', 'Фриланс'), ('sales', 'Продажи'), ('investment', 'Инвестиции'), ('services', 'Услуги'), ('other', 'Другое')], default='other', max_length=50),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'date'], name='core_expens_user_id_84343e_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['source_file'], name='core_expens_source__44095d_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['user', 'date'], name='core_income_user_id_3b2ac5_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['source_file'], name='core_income_source__654912_idx'),
        ),
    ]
