# Generated by Django 5.0.14 on 2025-12-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_expense_source_file_income_source_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('food', 'Еда'), ('transport', 'Транспорт'), ('entertainment', 'Развлечения'), ('shopping', 'Покупки'), ('subscriptions', 'Подписки'), ('education', 'Образование'), ('health', 'Здоровье'), ('beauty', 'Красота'), ('games', 'Игры'), ('rent', 'Аренда'), ('marketing', 'Маркетинг'), ('software', 'ПО/Сервисы'), ('equipment', 'Оборудование'), ('tax', 'Налоги'), ('other', 'Другое')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_type',
            field=models.CharField(choices=[('allowance', 'Карманные деньги'), ('part_time', 'Подработка'), ('gift', 'Подарок'), ('freelance', 'Фриланс'), ('sales', 'Продажи'), ('investment', 'Инвестиции'), ('services', 'Услуги'), ('salary', 'Зарплата'), ('bonus', 'Бонус'), ('other', 'Другое')], default='other', max_length=50),
        ),
    ]
