# Generated by Django 5.0.14 on 2025-12-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_expense_expense_type_alter_income_income_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='ai_category_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(default='KGS', max_length=3),
        ),
        migrations.AddField(
            model_name='expense',
            name='merchant',
            field=models.CharField(blank=True, help_text='Store or merchant name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='income',
            name='ai_category_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='currency',
            field=models.CharField(default='KGS', max_length=3),
        ),
        migrations.AddField(
            model_name='income',
            name='merchant',
            field=models.CharField(blank=True, help_text='Sender or business name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=10),
        ),
    ]
