# Generated by Django 5.0.14 on 2025-12-24 02:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('monthly_limit', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category Budget',
                'verbose_name_plural': 'Category Budgets',
                'indexes': [models.Index(fields=['user', 'is_active'], name='finance_cat_user_id_0c54f5_idx')],
                'unique_together': {('user', 'category')},
            },
        ),
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_key', models.CharField(db_index=True, help_text='Format: YYYY-MM', max_length=7)),
                ('total_income', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_expense', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Summary',
                'verbose_name_plural': 'Monthly Summaries',
                'ordering': ['-month_key'],
                'indexes': [models.Index(fields=['user', 'month_key'], name='finance_mon_user_id_0dcd0e_idx')],
                'unique_together': {('user', 'month_key')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Transaction date')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount (always positive, type determines if income or expense)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=10)),
                ('category', models.CharField(help_text='Category (e.g., Зарплата, Еда, Аренда)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('source', models.CharField(default='manual', help_text='Source of transaction (manual, imported, etc.)', max_length=50)),
                ('is_verified', models.BooleanField(default=True, help_text='Whether transaction is verified')),
                ('month_key', models.CharField(db_index=True, help_text='Format: YYYY-MM', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='finance_tra_user_id_3294c0_idx'), models.Index(fields=['user', 'month_key'], name='finance_tra_user_id_d2b585_idx'), models.Index(fields=['user', 'type'], name='finance_tra_user_id_35643f_idx')],
            },
        ),
    ]
