# Generated by Django 5.0.14 on 2025-12-24 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('KGS', 'Кыргызский сом'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('RUB', 'Российский рубль')], default='KGS', max_length=3)),
                ('locale', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('ky', 'Кыргызча')], default='ru', max_length=5)),
                ('timezone', models.CharField(default='Asia/Bishkek', max_length=50)),
                ('auto_anonymize', models.BooleanField(default=True, help_text='Anonymize data before sending to cloud LLM')),
                ('use_local_llm', models.BooleanField(default=False, help_text='Use local Ollama instead of cloud')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'indexes': [models.Index(fields=['user'], name='accounts_us_user_id_806298_idx')],
            },
        ),
    ]
