# Generated by Django 5.0.14 on 2025-12-24 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_key', models.CharField(blank=True, help_text='Format: YYYY-MM', max_length=7)),
                ('type', models.CharField(choices=[('monthly_report', 'Monthly Report'), ('goal_advice', 'Goal Progress Advice'), ('forecast_explanation', 'Forecast Explanation'), ('general_advice', 'General Financial Advice')], max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goals.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Recommendation',
                'verbose_name_plural': 'AI Recommendations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='ai_airecomm_user_id_d596f2_idx'), models.Index(fields=['user', 'goal'], name='ai_airecomm_user_id_8d9558_idx'), models.Index(fields=['month_key'], name='ai_airecomm_month_k_e8bf37_idx')],
            },
        ),
    ]
